[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
svm_clob = "JBphRWHYzHCiVvYB89vGM9NpaDmHbe1A9W156sRV52Bo"

[programs.testnet]
svm_clob = "JBphRWHYzHCiVvYB89vGM9NpaDmHbe1A9W156sRV52Bo"

[programs.devnet]
svm_clob = "JBphRWHYzHCiVvYB89vGM9NpaDmHbe1A9W156sRV52Bo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/deployer.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
