[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
svm_clob = "7YtJ5eYw1am3m73Yw2sh1QPWek3Ux17Ju1tp263h7YJB"

[programs.testnet]
svm_clob = "7YtJ5eYw1am3m73Yw2sh1QPWek3Ux17Ju1tp263h7YJB"

[programs.devnet]
svm_clob = "7YtJ5eYw1am3m73Yw2sh1QPWek3Ux17Ju1tp263h7YJB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/deployer.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
